[WebServerConfig]
server_name = "instaServer"
host = "0.0.0.0"
port = 8000
is_web_server = false
is_ssl = true


[JwtToken]
access_key = "insta_access"
refresh_key = "insta_refresh"
access_expire_min = 480
# access_expire_min = 1
refresh_expire_day = 7
check_duplicate = false

